// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.CardDeckShuffler
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("total_cards")]
        public long TotalCards { get; set; }

        [JsonProperty("decks_used")]
        public long DecksUsed { get; set; }

        [JsonProperty("includes_jokers")]
        public bool IncludesJokers { get; set; }

        [JsonProperty("shuffle_method")]
        public string ShuffleMethod { get; set; }

        [JsonProperty("cards")]
        public BottomCard[] Cards { get; set; }

        [JsonProperty("top_card")]
        public BottomCard TopCard { get; set; }

        [JsonProperty("bottom_card")]
        public BottomCard BottomCard { get; set; }

        [JsonProperty("sample_hand")]
        public BottomCard[] SampleHand { get; set; }
    }

    public partial class BottomCard
    {
        [JsonProperty("rank")]
        public RankUnion Rank { get; set; }

        [JsonProperty("suit")]
        public Suit Suit { get; set; }

        [JsonProperty("card")]
        public string Card { get; set; }

        [JsonProperty("short")]
        public string Short { get; set; }
    }

    public enum RankEnum { Ace, Jack, King, Queen };

    public enum Suit { Clubs, Diamonds, Hearts, Spades };

    public partial struct RankUnion
    {
        public RankEnum? Enum;
        public long? Integer;

        public static implicit operator RankUnion(RankEnum Enum) => new RankUnion { Enum = Enum };
        public static implicit operator RankUnion(long Integer) => new RankUnion { Integer = Integer };
    }
}
